### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by NotSoMik** [JasonBenfrin/Themis#1]
Hello, your project is amazing, can you also make other commands such as tictactoe, hangman, connect4, it will be very cool

**Comment by JasonBenfrin** [comment]
Hi! Thank you for visiting my repo! Thanks for the suggestion, I'll probably do it when I'm free. I never thought any of my repo will get visited XD. Thank you for the idea, it'll probably took me a while to do it. (I'm a busy student you know :) )

**Comment by NotSoMik** [comment]
Your repo is amazing thats why lmao, yea take your time :)
